AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  etc-sam-laravel12

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    LoggingConfig:
      LogFormat: JSON

Resources:
  LambdaFunctionLaravel:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      Runtime: provided.al2
      # Architectures:
      #   - arm64
      Handler: public/index.php
      CodeUri: .
      Environment:
          Variables:
            APP_STORAGE: /tmp
            APP_ENV: production
            APP_DEBUG: 'true'
            APP_KEY: base64:hryEkmpxpSdH82wE0mcLDUShCBXW+E1/aif6sOEVhmw=
            LOG_CHANNEL: stderr
      Layers:
        - arn:aws:lambda:ap-northeast-1:534081306603:layer:php-84-fpm:30

      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY


      Policies:
        - AWSLambdaBasicExecutionRole
